//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HEAPIFY_Manager_540.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsAdmin
    {
        public int id { get; set; }
        public int AdminAccountID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime Date { get; set; }
        public int AccountTypeID { get; set; }
        public int ModifyID { get; set; }
        public string History { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Modify Modify { get; set; }
    }
}
