//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HEAPIFY_Manager_540.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddLabReport
    {
        public int AddLabReportID { get; set; }
        public int PatientID { get; set; }
        public string WhereOrder { get; set; }
        public System.DateTime ResultDate { get; set; }
        public string Type { get; set; }
        public string Diagnoses { get; set; }
        public string Lab { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
