//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HEAPIFY_Manager_540.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllergiesName
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AllergiesName()
        {
            this.PatientAllergies = new HashSet<PatientAllergy>();
        }

        public int id { get; set; }
        public int AllergiesID { get; set; }
        public int AllergyTypeID { get; set; }
        public string AllergyName { get; set; }
    
        public virtual AllergyType AllergyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAllergy> PatientAllergies { get; set; }
    }
}
