//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HEAPIFY_Manager_540.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreateOrderInternal
    {
        public int id { get; set; }
        public int OrderID { get; set; }
        public int PatientID { get; set; }
        public int OrderingProvider { get; set; }
        public string Notes { get; set; }
        public string Diagnoses { get; set; }
        public string Lab { get; set; }
        public string Type { get; set; }
        public int ResponsibleOrder { get; set; }
        public string Stat { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
