//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HEAPIFY_Manager_540.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demographic
    {
        public int DemographicID { get; set; }
        public int PatientID { get; set; }
        public Nullable<int> OccupationID { get; set; }
        public int EthnicityID { get; set; }
        public int RaceID { get; set; }
        public Nullable<int> EmergencyContactID { get; set; }
        public int SmokingStatusID { get; set; }
        public int AlcoholStatusID { get; set; }
        public int ActiveSStatusID { get; set; }
        public int DrugAbuseID { get; set; }
    
        public virtual ActiveSStanding ActiveSStanding { get; set; }
        public virtual AlchoholStanding AlchoholStanding { get; set; }
        public virtual DrugAbuse DrugAbuse { get; set; }
        public virtual EmergencyContact EmergencyContact { get; set; }
        public virtual Ethnicity Ethnicity { get; set; }
        public virtual Occupation Occupation { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Race Race { get; set; }
        public virtual SmokingStanding SmokingStanding { get; set; }
    }
}
