//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HEAPIFY_Manager_540.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotesMedicalStaff
    {
        public int id { get; set; }
        public int NotesID { get; set; }
        public System.DateTime Date_Time_Recorded { get; set; }
        public string Notes { get; set; }
        public int PatientID { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
