//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HEAPIFY_Manager_540.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientImmunization
    {
        public int PatientImmunizationID { get; set; }
        public int PatientID { get; set; }
        public int ImmunizationID { get; set; }
        public System.DateTime DateGiven { get; set; }
    
        public virtual Immunization Immunization { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
