//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HEAPIFY_Manager_540.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vital
    {
        public int VitalID { get; set; }
        public System.DateTime DateAndTime { get; set; }
        public int BloodPressure { get; set; }
        public int Heart_Rate { get; set; }
        public int Respiratory_Rate { get; set; }
        public int Height_Length { get; set; }
        public double Weight { get; set; }
        public int Temperature { get; set; }
        public string Comments { get; set; }
        public int PatientID { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
